# Specific to Bash

# If not running interactively, don't do anything.
[[ $- != *i* ]] && return

# Include compatible dash conf
. "$MY_CONFIG_SH"/shell.sh

# HISTCONTROL
# ignorespace: lines which begin with a space character are not saved.
# ignoredups: causes lines matching the previous history entry to not be saved.
# ignoreboth: is shorthand for ignorespace and ignoredups.
# erasedups: causes all previous lines matching the current line to be removed
#            from the history list before that line is saved.
HISTCONTROL=ignoreboth:erasedups

# Number of commands to remember in the command history.
HISTSIZE=5000
# Maximum number of lines contained in the history file.
HISTFILESIZE=20000

# Append to the history file, don't overwrite it.
shopt -s histappend

# Git prompt
if [ -f /usr/share/git/completion/git-prompt.sh ]; then
  . /usr/share/git/completion/git-prompt.sh
fi

# fzf
if [ -x "$(command -v fzf)" ]; then
  . /usr/share/fzf/completion.bash
  . /usr/share/fzf/key-bindings.bash
fi
